# Generated by Django 4.2.23 on 2025-06-17 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('approved', '承認済み'), ('rejected', '拒否済み')], default='pending', max_length=10, verbose_name='ステータス')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='応募日時')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='応募者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='プロジェクト')),
            ],
            options={
                'unique_together': {('project', 'applicant')},
            },
        ),
    ]
